config/routes.rb
Rails.application.routes.draw do

  root 'selection_table#index'
  resources :welcome, only: [:show, :index]
  resources :selection_table, only: [:show, :select]
  resources :ordered_cocktails, only: [:destroy]
  get 'cocktail/:id' => 'welcome#show', as: :purchase
  get 'search_by_product(/:product)' => 'welcome#index', as: :search_by_product
  get 'addtocart/:id' => 'welcome#add_to_cart', as: :add_to_cart
  get 'cart', to: 'cart#show'
  get 'checkout', to: 'cart#checkout'
  get 'call', to: 'welcome#call_waiter'
  get 'select_table/:id' => 'selection_table#select', as: :select_table

  get "/images/thumbs/:id/:dims.jpg", to: "welcome#tumbs"

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/signup', to: 'users#new', via: 'get'

    resources :users, :products, :ingridients, :waiters, :tables

    resources :cocktails do
      resources :ingridients
    end

    match 'products/:name/:direction' => 'products#index',  via: 'get', as: :order_products
    match 'cocktails/:name/:direction' => 'cocktails#index', via: 'get', as: :order_cocktails

    match 'waiters/:id/update_tables' => 'waiters#update_tables',  via: 'post', as: :update_waiter_tables

  end

  namespace :api do
    namespace :v1 do
      resources :waiter
    end
  end

  namespace :employees do
    root 'waiter_workspace#index'
    resources :waiter_workspace, only: [:index]
    get 'waiter_workspace/clear_table' => 'waiter_workspace#clear_table', as: :clear_table
    get 'waiter_workspace/answer_alarm' => 'waiter_workspace#answer_alarm', as: :answer_alarm
    get 'waiter_workspace/status_update' => 'waiter_workspace#status_update', as: :status_update
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  include WelcomeHelper

  before_filter :find_item, only: [:show]

  before_action :verify_params!, only: [:add_to_cart]
  before_action :sum_to_pay, only: [:index,:show]
  before_action :get_current_table, only: [:index,:call_waiter, :add_to_cart]

  after_action :get_table_name, only: [:index]

  def index
    case
      when params.has_key?(:search)
        search_by_phrase
      when params.has_key?(:product)
        search_by_product
      else
        show_default
    end
    get_table_name
  end

  def show

  end

  def tumbs
    puts params
    image = Cocktail.find(1).image
    redirect_to image.url
  end

  def add_to_cart
    #check cocktail exists (verify_params)
    Order.add_cocktail_to_order @cocktail_id, @current_table
    redirect_to action: 'index'
  end

  def call_waiter
    Table
        .where(:id => @current_table)
        .update_all(:status => Table.statuses[:waiting])

    redirect_to_back
  end



  private
  def find_item
    @cocktail= Cocktail.find_with_includes params[:id]
  end

  def filter_by field
    if params[field].present?
      @cocktails = @cocktails.select { |v| v.send(field) == params[field] }
    end
    @cocktails
  end

  def show_default
    @cocktails = Cocktail.all_with_includes
    group_and_filter_by :type
  end


  def search_by_phrase
    @cocktails = {}
    @cocktails["name containing '#{params[:search].to_s}'"] = Cocktail.search_by_name(params[:search]).all_with_includes
    @cocktails["ingridient name containing '#{params[:search].to_s}'"] =
        Cocktail.search_by_ingridients_name(params[:search]).all_with_includes

  end

  def search_by_product
    if params[:product].present?
      @cocktails = Cocktail.all_with_includes_by_product params[:product]
    else
      @cocktails = Cocktail.all_with_includes
    end
    group_and_filter_by :type

  end

  def group_and_filter_by field
    # if params[field].present?
    @cocktails = filter_by(field)
    #else
    @cocktails = @cocktails.group_by { |c| c.send(field) }
    #end

  end

  def redirect_to_back(error_message='')
    if error_message.present?
      flash[:warning] = error_message
    end
    redirect_to request.referer.blank? ? root_url : request.referer
  end

  def verify_params!
    @cocktail_id = params[:id]
    unless @cocktail_id.blank?
      if Cocktail.find_by(id: @cocktail_id).blank?
        redirect_to_back "Can not find cocktail with id #{@product_id}"
      end
    end
  end

  def sum_to_pay
    @sum = Order.sum_to_pay get_current_table
  end

  def get_current_table
    @current_table = get_current_table_id

  end

  def get_table_name
    @table_name = Table.find(@current_table).name
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def set_current_table_id(table_id)
    cookies.permanent[:table_id] = table_id
  end

  def get_current_table_id
    @current_table_id||=cookies[:table_id]
  end

end

app/views/welcome/_group.html.erb
<% if (cocktails.present?) %>
<div class="body_panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= type.capitalize.pluralize%></h3>
  </div>
  <div class="panel-body">
    <div class="row-eq-height">
      <% cocktails.each do |cocktail| %>
          <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="thumbnail">
              <div style="text-align: center">
                <%= link_to purchase_path(cocktail), class: "container_relative" do %>
                    <%= image_tag(cocktail.image_url, class: "img-thumbnail") %>
                    <div class="put_bottom_right">
                      <h3><span class="label label-success"><%= cocktail.price %></span></h3>
                    </div>
                <% end %>
              </div>
              <div class="caption">
                <h3 class="hide_overflow"><%= cocktail.name %></h3>

                <p style="height: 36px">
                  <% cocktail.ingridients.each do |ingridient| %>
                      <span class="label ">
                        <%= link_to ingridient.product.name, search_by_product_path(ingridient.product.name) %>
                      </span>
                  <% end %>
                </p>

                <p>
                  <%= link_to add_to_cart_path(cocktail.id), { :class=>"btn btn-primary", :role=>"button" } do %>
                      <i class="glyphicon glyphicon-shopping-cart"></i> Add To Cart
                  <% end %>
                  <a href="#" class="btn btn-default" role="button">Button</a></p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/welcome/_header.html.erb
<% cocktails_present = false
   @cocktails.each do |type, cocktails|
     if (cocktails.present?)
       cocktails_present = true
       break
     end
   end
%>

<%= page_header 'Cocktails', ' ' << (@cocktails.blank? || !cocktails_present ? 'are not available' : '') %>

app/views/welcome/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= welcome_index_path %>">Welcome</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to root_path do %>
              <i class="glyphicon glyphicon-glass"><%= 'Table '<< @table_name %></i>
          <% end %>
        </li>

        <li>
          <%= link_to call_path do %>
              <i class="glyphicon glyphicon-bell"></i>
          <% end %>
        </li>
        <li>
          <%= link_to cart_path do %>
              <i class="glyphicon glyphicon-shopping-cart"> <%= (@sum > 0 ? '($'<< @sum.to_s<<')' : '') %></i>
          <% end %>
        </li>
        <li class="dropdown navbar-right">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
            Show <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All', welcome_index_path %></li>
            <li><%= link_to 'Shorts', welcome_index_path(:type => 'short') %></li>
            <li><%= link_to 'Longs', welcome_index_path(:type => 'long') %></li>
          </ul>
        </li>
      </ul>

      <%= form_tag(welcome_index_path, :method => "get", class: "navbar-form navbar-right", id: "search-form") do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<% content_for :right_col do %>
    Hello this is right col
<% end %>

<% content_for :left_col do %>
    This is left column
<% end %>

<%= render partial: 'header', locals: {cocktails: @cocktails} %>

<% @cocktails.each do |type, cocktails| %>
    <%= render partial: 'group', locals: {cocktails: cocktails, type: type} %>
<% end %>

<%= debug params%>

app/views/welcome/show.html.erb
<div class="page-header">
  <h1><%= @cocktail.name %>
    <small><%= "#{@cocktail.value}ml" %></small>

  <div class="right" role="group">
    <small>
    Price: <%= "#{@cocktail.price}$" %>
      </small>
  </div>
  </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-5 col-md-6 text-center">
        <%= image_tag(@cocktail.image_url, size: '500', class: "img-thumbnail") %>
      </div>
      <br class="visible-xs-block">

      <div class="col-sm-7 col-md-6">
        <div>
          <div class="panel panel-info">
            <ul class="list-group">
              <% @cocktail.ingridients.each do |ingridient| %>
                  <li class="list-group-item li-vert-align">
                    <%= image_tag(ingridient.product.image_url, size: '50', class: "img-thumbnail") %>
                    <%= "#{ingridient.product.name} #{ingridient.value}ml" %>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Description</h3>
      </div>
      <div class="panel-body">
        <%= @cocktail.description %>
      </div>
    </div>

  </div>
</div>