config/routes.rb
Rails.application.routes.draw do

  root 'selection_table#index'
  resources :welcome, only: [:show, :index]
  resources :selection_table, only: [:show, :select]
  resources :ordered_cocktails, only: [:destroy]
  get 'cocktail/:id' => 'welcome#show', as: :purchase
  get 'search_by_product(/:product)' => 'welcome#index', as: :search_by_product
  get 'addtocart/:id' => 'welcome#add_to_cart', as: :add_to_cart
  get 'cart', to: 'cart#show'
  get 'checkout', to: 'cart#checkout'
  get 'call', to: 'welcome#call_waiter'
  get 'select_table/:id' => 'selection_table#select', as: :select_table

  get "/images/thumbs/:id/:dims.jpg", to: "welcome#tumbs"

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/signup', to: 'users#new', via: 'get'

    resources :users, :products, :ingridients, :waiters, :tables

    resources :cocktails do
      resources :ingridients
    end

    match 'products/:name/:direction' => 'products#index',  via: 'get', as: :order_products
    match 'cocktails/:name/:direction' => 'cocktails#index', via: 'get', as: :order_cocktails

    match 'waiters/:id/update_tables' => 'waiters#update_tables',  via: 'post', as: :update_waiter_tables

  end

  namespace :api do
    namespace :v1 do
      resources :waiter
    end
  end

  namespace :employees do
    root 'waiter_workspace#index'
    resources :waiter_workspace, only: [:index]
    get 'waiter_workspace/clear_table' => 'waiter_workspace#clear_table', as: :clear_table
    get 'waiter_workspace/answer_alarm' => 'waiter_workspace#answer_alarm', as: :answer_alarm
    get 'waiter_workspace/status_update' => 'waiter_workspace#status_update', as: :status_update
  end
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  mount_uploader :image, CocktailImageUploader
  has_many :ingridients, dependent: :destroy
  has_many :products, through: :ingridients

  has_many :ordered_cocktails
  has_many :orders, through: :ordered_cocktails

  before_save { self.name = name.titleize }

  validates :name, presence: true, allow_blank: false
  validate :validate_ingridients

  scope :search_by_name, -> (name) { where("cocktails.name LIKE ?", "%#{name}%") }

  scope :search_by_ingridients_name, ->(name) {
    eager_load(:products)
        .where("products.name LIKE ?", "%#{name}%")
  }

  def validate_ingridients
    if ingridients.size < 2
      errors.add(:ingridients, 'quantity must be greater than one')
    elsif ingridients.select { |ingridient| ingridient.product.product_type =='drink' }.size<1
      errors.add(:ingridients, 'with product type \'drink\' must be present in cocktail (minimum is 1 product)')
    end
  end

  accepts_nested_attributes_for :ingridients, reject_if: lambda { |attributes| attributes[:value].blank? && attributes[:product_id].blank? }

  def value
    ingridients.inject(0) { |sum, ingridient|
      sum + (ingridient.product.product_type == 'drink' ? ingridient.value : 0)
    }
  end

  def price
    ingridients.inject(0) { |price, ingridient|
      price + (ingridient.value / ingridient.product.min_value) * ingridient.product.price
    }.ceil
  end

  def self.find_with_includes (id)
    self.includes(ingridients: [:product]).find id

  end

  def self.all_with_includes
    self.includes(ingridients: [:product]).all

  end

  def self.all_with_includes_by_product product

    self.joins(:products).includes(ingridients: [:product]).where("products.name=?", product)

  end

  def type
    value < 150 ? 'short' : 'long'
  end


end

app/controllers/admin/cocktails_controller.rb
class Admin::CocktailsController < Admin::SignedApplicationController
  layout 'application_admin'

  before_filter :find_item, only: [:edit, :update, :destroy, :show]

  before_action :verify_params!, :before_new, only: [:new]

  INGRIDIENt_MAX_COUNT =5

  def index
    @cocktails = Cocktail.all_with_includes
    @items_count = @cocktails.size
    @per_page = PAGINATION_PER_PAGE

    if params[:name].present?
      if 'price' == params[:name]
        @cocktails = @cocktails.sort_by{ |a| a.price } if 'asc' == params[:direction]
        @cocktails = @cocktails.sort_by{ |a| -a.price } if 'desc' == params[:direction]
      else
        @cocktails = @cocktails.order("#{params[:name]} #{params[:direction]}")
      end
    end
    @cocktails = paginate(@cocktails, params[:page], @per_page)
  end

  def new
    prepare_ingridient_items
  end

  def items_params
    params.require(:cocktail).permit(:id, :name, :image, :remove_image, :description, ingridients_attributes: [:id, :value, :product_id, :cocktail_id])
  end

  def create
    @cocktail = Cocktail.create items_params
    if @cocktail.errors.empty?
      flash[:success] = "Cocktail \'#{@cocktail.name.humanize}\' was created successfully"
      redirect_to action: :index
    else
      flash[:warning] = @cocktail.errors.full_messages.to_sentence
      prepare_ingridient_items
      render :new
    end
  end

  def update
    @cocktail.update_attributes items_params
    if @cocktail.errors.empty?
      flash[:success] = "Cocktail \'#{@cocktail.name.humanize}\' was updated successfully"
      redirect_to action: :index
    else
      flash[:warning] = @cocktail.errors.full_messages.to_sentence
      prepare_ingridient_items
      render :edit
    end
  end


  def edit
    prepare_ingridient_items
  end

  def show

  end

  def destroy
    @cocktail.destroy
    if @cocktail.errors.empty?
      flash[:success] = "Cocktail '#{@cocktail.name}' was removed successfully"
      redirect_to action: :index
    else
      flash[:warning] = @cocktail.errors.full_messages.to_sentence
      render action: :index
    end
  end

  private
  def find_item
    @cocktail= Cocktail.find_with_includes params[:id]
  end

  def redirect_to_back error_message
    if error_message.present?
      flash[:warning] = error_message
    end
    redirect_to request.referer.blank? ? root_url : request.referer
  end

  def prepare_ingridient_items
    (INGRIDIENt_MAX_COUNT - @cocktail.ingridients.size).times {
      @cocktail.ingridients.build
    }
  end

  def verify_params!
    @product_id = params[:product]
    unless @product_id.blank?
      if Product.find_by(id: @product_id).blank?
        redirect_to_back "Can not find product with id #{@product_id}"
      end
    end
  end

  def before_new
    @cocktail = Cocktail.new
    product_id = params[:product]

    if validate_product_id? product_id
      @cocktail.ingridients.build(product_id: product_id)
    else
      redirect_to_back "Can not find product with id #{@product_id}"
    end
  end

  def validate_product_id? id
    result = true
    unless id.blank?
      product = Product.find_by(id: id)
      if product.blank?
        result false
      end
    end
    result
  end

end

app/controllers/api/v1/cocktails_controller.rb
class Api::V1::CocktailsController < Api::ApiApplicationController

  def index
    @cocktails = Cocktail.all_with_includes
    render json: @cocktails, :include => {
        :ingridients => {
            :include => {:product => {:except => [:created_at, :updated_at]}},
            :except => [:created_at, :updated_at]
        } },
           :except => [:created_at, :updated_at]
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/admin/cocktails/_form.html.erb
<div class="body_panel panel-default">
  <div class="panel-heading">
    <%= form_field_text(f, :name) %>
  </div>

  <div class='field form-group'>
    <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_area :description, class: 'form-comtrol', rows: 5 %>
    </div>
    </div>

  <div class='field form-group'>
    <%= f.label :image, class: 'col-md-2 control-label' %>
    <div class='col-sm-3'>
      <%= f.file_field :image, multiple: false %>
    </div>
  </div>


  <% if @cocktail.image? %>
      <div class='field form-group'>
        <div class='col-md-2 control-label'></div>

        <div class='col-sm-5'>
          <%= f.check_box :remove_image %>
        </div>
      </div>

      <div class="field form-group">
        <div class='col-md-2 control-label'></div>
        <div class='col-sm-10'>
          <%= image_tag(@cocktail.image_url, size: '380', class: "img-thumbnail")%>
        </div>
      </div>

  <% end %>

</div>


<div class="body_panel panel-default">
  <div class="panel-body">
    <legend><%= :ingridients %></legend>
    <%= f.fields_for :ingridients do |ingridients_form| %>
      <div class="field form-group">
        <div class="form-group row">
          <%= form_number_field(ingridients_form,:value) %>
          <%= form_select_field(ingridients_form, :product_id, Product.all, :id, :tname, {:prompt => true}) %>
        </div>
      </div>
    <% end %>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save"%>
      </div>
    </div>
  </div>
</div>

app/views/admin/cocktails/edit.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [:admin, @cocktail] do |f| %>
    <%= render partial: 'form', locals:{f: f} %>
<% end %>

app/views/admin/cocktails/index.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %>
    <% if @cocktails.empty? %>
    <small> have not been created yet</small>
    <% else %>
        <small><%= action_name %></small>
    <% end %>
    <div class="btn-group right" role="group">
      <%= link_to 'Add', new_admin_cocktail_path %>
    </div>
  </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <table class="table table-hover">
      <tr>
      <th>Id</th>
      <th>Name
        <%= get_sort_buttons(admin_order_cocktails_path(:name, 'asc'), admin_order_cocktails_path(:name, 'desc')) %>
      </th>
      <th>Value</th>
      <th>Price
        <%= get_sort_buttons(admin_order_cocktails_path(:price, 'asc'), admin_order_cocktails_path(:price, 'desc')) %>
      </th>
        <th>Type</th>
      <th></th>
      </tr>
      <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.id %></td>
        <td><%= link_to cocktail.name, admin_cocktail_path(cocktail) %></td>
        <td><%= cocktail.value %></td>
        <td><%= cocktail.price %></td>
        <td><%= cocktail.type.capitalize %></td>
        <td>
          <div class="btn-group" role="group">
            <%= link_to 'edit', edit_admin_cocktail_path(cocktail) %>
            <%= link_to 'remove', admin_cocktail_path(cocktail), method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        </td>
      </tr>
          <% end %>
    </table>
  </div>
</div>
<div class="body_panel panel-default">
    <%= draw_pagination @items_count, @per_page %>
</div>

app/views/admin/cocktails/new.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [:admin, @cocktail]  do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <!--<br>-->
    <%#= f.submit name: 'create', value: 'create' %>
    <%#= f.submit name: 'continue', value: 'create and continue' %>
<% end %>

app/views/admin/cocktails/search.html.erb
<h1>Hi</h1>
<% if @cocktail.empty? %>
<h2>Products list is empty</h2>
    <% else %>
    <table border="1">
      <tr>
        <th>Id</th>
        <th>Product</th>
        <th>Cost Price</th>
        <th>Min Value</th>
        <th>Type</th>
        <th>Edit</th>
        <th>Remove</th>
      </tr>
      <% @cocktail.each do |cocktail| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.cost_price %></td>
        <td><%= product.min_value %></td>
        <td><%= product.product_type %></td>
        <td><%= link_to 'edit', edit_admin__product_path(product) %></td>
        <td><%= link_to 'remove', admin_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
          <% end %>
        </table>
<% end %>

app/views/admin/cocktails/show.html.erb
<div class="page-header">
  <h1><%= @cocktail.name %>
    <small><%= "#{@cocktail.value}ml" %></small>
    <div class="btn-group right" role="group">
      <%= link_to 'All', {action: :index} %>
      <%= link_to 'Edit', {action: :edit} %>
      <%= link_to 'Remove', admin_cocktail_path(@cocktail), method: :delete, data: {confirm: 'Are you sure?'} %>
      <%= link_to 'Add Ingridient', new_admin_cocktail_ingridient_path(@cocktail) %>
    </div>
  </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-5 col-md-6 text-center">
        <%= image_tag(@cocktail.image_url, size: '500', class: "img-thumbnail") %>
      </div>
      <br class="visible-xs-block">

      <div class="col-sm-7 col-md-6">
        <div>
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Details</h3>
            </div>
            <ul class="list-group">
              <li class="list-group-item"><%= "ID: #{@cocktail.id }" %></li>
              <li class="list-group-item"><%= "Name: #{@cocktail.name }" %></li>
              <li class="list-group-item"><%= "Min value: #{@cocktail.value}" %></li>
              <li class="list-group-item"><%= "Cost price: #{@cocktail.price}" %></li>
            </ul>
          </div>
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Ingridients</h3>
            </div>
            <ul class="list-group">
              <% @cocktail.ingridients.each do |ingridient| %>
                  <li class="list-group-item li-vert-align">
                    <%= image_tag(ingridient.product.image_url, size: '50', class: "img-thumbnail") %>
                    <%= "#{ingridient.product.name} #{ingridient.value}ml" %>
                    <div class="btn-group-wrapper">
                      <div class="btn-group li-vert-align" role="group">
                        <%= link_to 'Edit', edit_admin_cocktail_ingridient_path(@cocktail, ingridient) %>
                        <%= link_to 'Remove', admin_cocktail_ingridient_path(@cocktail, ingridient), method: :delete, data: {confirm: 'Are you sure?'} %>
                      </div>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Description</h3>
      </div>
      <div class="panel-body">
        <%= @cocktail.description %>
      </div>
    </div>

  </div>
</div>