config/routes.rb
Rails.application.routes.draw do

  root 'selection_table#index'
  resources :welcome, only: [:show, :index]
  resources :selection_table, only: [:show, :select]
  resources :ordered_cocktails, only: [:destroy]
  get 'cocktail/:id' => 'welcome#show', as: :purchase
  get 'search_by_product(/:product)' => 'welcome#index', as: :search_by_product
  get 'addtocart/:id' => 'welcome#add_to_cart', as: :add_to_cart
  get 'cart', to: 'cart#show'
  get 'checkout', to: 'cart#checkout'
  get 'call', to: 'welcome#call_waiter'
  get 'select_table/:id' => 'selection_table#select', as: :select_table

  get "/images/thumbs/:id/:dims.jpg", to: "welcome#tumbs"

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/signup', to: 'users#new', via: 'get'

    resources :users, :products, :ingridients, :waiters, :tables

    resources :cocktails do
      resources :ingridients
    end

    match 'products/:name/:direction' => 'products#index',  via: 'get', as: :order_products
    match 'cocktails/:name/:direction' => 'cocktails#index', via: 'get', as: :order_cocktails

    match 'waiters/:id/update_tables' => 'waiters#update_tables',  via: 'post', as: :update_waiter_tables

  end

  namespace :api do
    namespace :v1 do
      resources :waiter
    end
  end

  namespace :employees do
    root 'waiter_workspace#index'
    resources :waiter_workspace, only: [:index]
    get 'waiter_workspace/clear_table' => 'waiter_workspace#clear_table', as: :clear_table
    get 'waiter_workspace/answer_alarm' => 'waiter_workspace#answer_alarm', as: :answer_alarm
    get 'waiter_workspace/status_update' => 'waiter_workspace#status_update', as: :status_update
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ProductImageUploader
  has_many :ingridients
  has_many :cocktails, through: :ingridients, dependent: :destroy

  before_save {self.name = name.titleize}

  validates :cost_price, :min_value, :product_type, presence: true
  validates :name, presence: true, allow_blank: false
  validates :cost_price, :min_value, numericality: {greater_than: 0}

  @@product_types =['drink','not drink']

  @@tax = 0.04
  @@markup_percent =0.5

  def price
    cost_price + markup + (markup * @@tax)
  end

  def markup
    cost_price*@@markup_percent

  end

  def self.product_types
    @@product_types
  end

  def tname
    self.name+'--'+self.product_type
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::SignedApplicationController

  before_filter :find_item, only: [:edit, :update, :destroy, :show]

  def index
    @products = Product.all
    @products_count = @products.size
    @per_page = PAGINATION_PER_PAGE
    if params[:name].present?
      @products = @products.order("#{params[:name]} #{params[:direction]}")
    end
    @products = paginate(@products, params[:page], @per_page)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create item_params
    redirect_to action: 'index'
  end

  def item_params
    params.require(:product).permit(:id, :name, :image, :remove_image, :cost_price, :min_value, :product_type)
  end

  def edit

  end

  def update
    @product.update_attributes item_params
    if @product.errors.empty?
        redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to action: 'index'
  end

  def show

  end

  def search
    @products= Product.where("name LIKE ?", "%#{params[:name]}%")
  end

  private
  def find_item
    @product= Product.where(id: params[:id]).first
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="body_panel panel-default">

  <div class='field form-group'>
    <%= f.label :image, class: 'col-md-2 control-label' %>
    <div class='col-sm-3'>
      <%= f.file_field :image, multiple: false %>
    </div>
  </div>

  <% if @product.image? %>
      <div class='field form-group'>
        <div class='col-md-2 control-label'></div>

        <div class='col-sm-5'>
          <%= f.check_box :remove_image %>
        </div>
      </div>

      <div class="field form-group">
        <div class='col-md-2 control-label'></div>
        <div class='col-sm-10'>
          <%= image_tag(@product.image_url, size: '380', class: "img-thumbnail")%>
        </div>
      </div>

  <% end %>

  <div class="panel-body">
    <%= form_field_text(f, :name) %>
    <div class="row field form-group">
      <%= form_field_row_numeric(f, :cost_price) %>
      <%= form_field_row_numeric(f, :min_value) %>
      <%= form_field_row_select(f, :type, :product_type, Product.product_types) %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save" %>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [:admin, @product] do |f| %>
    <%= render partial: 'form', locals:{f: f} %>
<% end %>

app/views/admin/products/index.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %>
    <% if @products.empty? %>
        <small> have not been created yet</small>
    <% else %>
        <small><%= action_name %></small>
    <% end %>
    <div class="btn-group right" role="group">
      <%= link_to 'Add', {action: :new} %>
    </div>
  </h1>
</div>


<div class="body_panel panel-default">
  <div class="panel-body">
    <table class="table table-hover">
      <tr>
        <th>Id</th>
        <th>Product
          <%= get_sort_buttons(admin_order_products_path(:name, 'asc'), admin_order_products_path(:name, 'desc')) %>
        </th>
        <th>Cost Price
          <%= get_sort_buttons(admin_order_products_path(:cost_price, 'asc'), admin_order_products_path(:cost_price, 'desc')) %>
        </th>
        <th>Min Value</th>
        <th>Price</th>
        <th>Type</th>
        <th>Action</th>
      </tr>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.cost_price %></td>
            <td><%= product.min_value %></td>
            <td><%= product.price %></td>
            <td><%= product.product_type %></td>
            <td>
              <div class="btn-group" role="group">
                <%= link_to 'edit', edit_admin_product_path(product) %>
                <%= link_to 'remove',admin_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %>
              </div>
            </td>
          </tr>
      <% end %>
    </table>

    </div>
  </div>
<div class="body_panel panel-default">
  <%= draw_pagination @products_count, @per_page %>
</div>

app/views/admin/products/new.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [:admin, @product] do |f| %>
 <%= render partial: 'form', locals:{f: f} %>
<% end %>

app/views/admin/products/search.html.erb
<h1>Hi</h1>
<% if @products.empty? %>
<h2>Products list is empty</h2>
    <% else %>
    <table border="1">
      <tr>
        <th>Id</th>
        <th>Product</th>
        <th>Cost Price</th>
        <th>Min Value</th>
        <th>Type</th>
        <th>Edit</th>
        <th>Remove</th>
      </tr>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.cost_price %></td>
        <td><%= product.min_value %></td>
        <td><%= product.product_type %></td>
        <td><%= link_to 'edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'remove', admin_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
          <% end %>
        </table>
<% end %>

app/views/admin/products/show.html.erb
<div class="page-header">
  <h1><%= @product.name %>
    <small><%= "#{@product.min_value}ml"%></small>
    <div class="btn-group right" role="group">
      <%= link_to 'All', {action: :index} %>
      <%= link_to 'Edit', {action: :edit} %>
      <%= link_to 'Remove', product_path(@product), method: :delete, data: {confirm: 'Are you sure?'} %>
      <%= link_to 'Add Cocktail', new_cocktail_path(product: @product.id) %>
    </div>
    </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag(@product.image_url, size: '350', class: "img-thumbnail")%>
      </div>
      <br class="visible-xs-block visible-sm-block">
      <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Details</h3>
        </div>
        <ul class="list-group">
          <li class="list-group-item"><%= "ID: #{@product.id}" %></li>
          <li class="list-group-item"><%= "Name: #{@product.name}" %></li>
          <li class="list-group-item"><%= "Min value: #{@product.min_value}ml" %></li>
          <li class="list-group-item"><%= "Cost price: #{@product.cost_price}$" %></li>
          <li class="list-group-item"><%= "Type: #{@product.product_type}" %></li>
        </ul>
      </div>
    </div>
  </div>
  </div>
</div>