config/routes.rb
Rails.application.routes.draw do

  root 'selection_table#index'
  resources :welcome, only: [:show, :index]
  resources :selection_table, only: [:show, :select]
  resources :ordered_cocktails, only: [:destroy]
  get 'cocktail/:id' => 'welcome#show', as: :purchase
  get 'search_by_product(/:product)' => 'welcome#index', as: :search_by_product
  get 'addtocart/:id' => 'welcome#add_to_cart', as: :add_to_cart
  get 'cart', to: 'cart#show'
  get 'checkout', to: 'cart#checkout'
  get 'call', to: 'welcome#call_waiter'
  get 'select_table/:id' => 'selection_table#select', as: :select_table

  get "/images/thumbs/:id/:dims.jpg", to: "welcome#tumbs"

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/signup', to: 'users#new', via: 'get'

    resources :users, :products, :ingridients, :waiters, :tables

    resources :cocktails do
      resources :ingridients
    end

    match 'products/:name/:direction' => 'products#index',  via: 'get', as: :order_products
    match 'cocktails/:name/:direction' => 'cocktails#index', via: 'get', as: :order_cocktails

    match 'waiters/:id/update_tables' => 'waiters#update_tables',  via: 'post', as: :update_waiter_tables

  end

  namespace :api do
    namespace :v1 do
      resources :waiter
    end
  end

  namespace :employees do
    root 'waiter_workspace#index'
    resources :waiter_workspace, only: [:index]
    get 'waiter_workspace/clear_table' => 'waiter_workspace#clear_table', as: :clear_table
    get 'waiter_workspace/answer_alarm' => 'waiter_workspace#answer_alarm', as: :answer_alarm
    get 'waiter_workspace/status_update' => 'waiter_workspace#status_update', as: :status_update
  end
end

app/views/layouts/_admin_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CB Panel</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if signed_in? %>
          <ul class="nav navbar-nav">
            <li> <%= link_to 'Products', admin_products_path %></li>
            <li> <%= link_to 'Cocktails', admin_cocktails_path %></li>
            <li> <%= link_to 'Tables', admin_tables_path %></li>
            <li> <%= link_to 'Waiters', admin_waiters_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text"> logged as <%= link_to current_user.name, admin_user_path(current_user) %></p></li>
            <li><p class="navbar-text"><%= link_to 'Sign Out', admin_signout_path, method: 'delete' %></p></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text"><%= link_to 'Sign In', admin_signin_path %></p></li>
            <li><p class="navbar-text"><%= link_to 'Sign Up', admin_signup_path %></p></li>
          </ul>
      <% end %>

    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cocktailbar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}")  %>
<% end %>

<%= render partial: 'menu' %>

<%= yield %>
<%= yield :right_col %>
<%= yield :left_col %>

</body>
</html>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cocktailbar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/admin_menu' %>
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}")  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/application_employee.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cocktailbar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= employees_root_path %>">Workplace</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <%= form_tag({:controller => "waiter_workspace", :action => "index"}, method: :get, enforce_utf8: false,class: "navbar-form navbar-left") do %>
          <div class="dropdown">
          <%= select_tag 'id', options_from_collection_for_select(Waiter.hired, 'id', 'fullname'),prompt: 'select waiter',onchange: "this.form.submit();"%>
          </div>
      <% end %>
      <div class="navbar-right">
      <% if @waiter%>
          <h4 class="navbar-text"><%= "Hello, #{@waiter.firstname}" %></h4>
          <p class="navbar-text"><%= "Your all time earnings: #{@waiter.worksets.sum(:total_earned)}" %> <span class="glyphicon glyphicon-usd" aria-hidden="true"></span></p>
          <%end%>
      <button type="button" class="navbar-btn"  aria-label="Left Align" > <%= link_to '<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>'.html_safe,'', { :onclick => "history.go(0)" }%>

      </button></div>
    </div>
  </div>
</nav>

<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}")  %>
<% end %>


<%= yield %>

</body>
</html>